# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd8bd43f18866579ef4a25636fcb7c12bd3973ec8950d59142d9770d929260a4f16523739c10ba32514bfee653c3128a041af5ff10e9a188d1425b48684bf86d
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://loaclhost:3000

test:
  secret_key_base: 0cd89fe4df6dce4ab78735ff31300db8a88f299c09aea450bdd4874ebe9f8cc4f51f2bd9573d7b745d22470ab74e58dcbb489a6a062ad1bed01510b0c5599f9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  paypal_host: https://www.paypal.com
  app_host: http://www.gotealeaf.com/

